version: '3.4'
networks:
   wavesenterprise-network:
     driver: bridge
services:
  db-app:
    image: postgres:11
    restart: always
    container_name: db-app
    hostname: db-app
    env_file: ./config/db-app/env
    environment:
      - POSTGRES_MULTIPLE_DATABASES=db_oauth2,db_identity,db_files,db_example_app
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./config/db-app/scripts:/docker-entrypoint-initdb.d/
      - ./data/db-app/pg:/var/lib/postgresql/data
    networks:
      - wavesenterprise-network
  vst-identity:
    image: registry.wavesenterprise.com/icore/vst-identity:1.8.3-SNAPSHOT-20210208181944-v.1.0.0-RC1-63-g61077d9
    hostname: vst-identity
    restart: always
    container_name: vst-identity
    expose:
      - 8080
    ports:
      - 8090:8080
    env_file: ./config/vst-identity/env
    networks:
      - wavesenterprise-network
  vst-oauth2:
    image: registry.wavesenterprise.com/icore/vst-oauth2:1.6.1-SNAPSHOT-20210120135413-v.1.0.0-RC1-80-g71b2912
    hostname: vst-oauth2
    restart: always
    container_name: vst-oauth2
    expose:
      - 8080
    ports:
      - 8091:8080
    env_file: ./config/vst-oauth2/env
    volumes:
      - "./config/vst-oauth2/oauth-clients.yml:/opt/oauth-clients.yml"
      - "./config/vst-oauth2/user-companies.json:/opt/user-companies.json"
    networks:
      - wavesenterprise-network
    vst-files:
      image: registry.wavesenterprise.com/icore/vst-files:1.8.1-support-last_prod_version-SNAPSHOT-20210211230708-1.8.1-support
      hostname: vst-files
      restart: always
      container_name: vst-files
      expose:
        - 8080
      ports:
        - 8092:8080
      env_file: ./config/vst-files/env
      networks:
        - wavesenterprise-network