we-oauth2:
  additional:
    clientsDetails:
      - clientId: api-example-app
        clientSecret: $2a$10$fdBz3//en5qdLLuZB3U/uuuOtAqwGERyjM1YfFMpp3BNrJAaNKzKq # example-app-secret
        resourceIds:
          - vst-oauth2
          - vst-identity
          - vst-files
          - example-app
        scope:
          - read
          - vst-client
        authorizedGrantTypes:
          - password
          - refresh_token
        registeredRedirectUri:
          - http://localhost/test
        authorities:
          - ROLE_TRUSTED_CLIENT
          - WE_IDENTITY_READ

      - clientId: example-app
        clientSecret: $2a$10$RvJtlLwnvnRDXa2W41MS6e6cqFoSgOuCixWAUGOAa34GzlhlL.JoK # example-app-secret
        resourceIds:
          - vst-identity
          - vst-files
          - vst-oauth2
        scope:
          - read
        authorizedGrantTypes:
          - client_credentials
        authorities:
          - ROLE_TRUSTED_CLIENT
          - WE_IDENTITY_READ
          - WE_IDENTITY_WRITE
          - WE_PRIVACY_READ
          - WE_PRIVACY_WRITE
          - WE_OAUTH2_WRITE
          - WE_OAUTH2_READ
